import firebase from "firebase";

export type StudentDetailsType = {
  faculty_number: string;
  fa: string;
  admission_no: string;
  alternate_number: string;
  blood_group: string;
  cast: string;
  city: string;
  class: number;
  class_roll: string;
  contact_number: string;
  date_of_addmission: string;
  dob: string;
  email: string;
  father_name: string;
  father_occupation: string;
  father_qualification: string;
  gender: string;
  id: string;
  mother_name: string;
  mother_occupation: string;
  motherqualifiation: string;
  postal_code: string;
  profil_url: string;
  religion: string;
  section: string;
  state: string;
  student_id: string;
  student_name: string;
  monthly_fee?: number;
  computer_fee: number;
  created_at?: firebase.firestore.Timestamp | firebase.firestore.FieldValue;
  transportation_fee: number;
  generated_fee: string[];
  fee_discount?: number;
};
